### ISSUE TITLE
recaptcha2 integration

### ISSUE THREAD

**Issue by saotomaster** [MrDioamDev/risus2#1]
after adding the  recaptcha keys in admin panel... when i try to sign up it says...
No se puede conectar con reCAPTCHA. Comprueba tu conexión e inténtalo de nuevo.

despues de agregar las llaves de recatptcha... al tratar de ir a registro sale el mensaje...
No se puede conectar con reCAPTCHA. Comprueba tu conexión e inténtalo de nuevo....

**Comment by MrDioamDev** [comment]
Hola.
Resulta que las keys por defecto no las puedo lograr hacer que funcionen en todos los sitios sin tener que cambiarlas.
Estoy tratando de buscar una solución!

**Comment by saotomaster** [comment]
gracias!

**Comment by saotomaster** [comment]
con que llaves lo instalaste tu? en tu sitio funciona...

**Comment by MrDioamDev** [comment]
Las instalé con unas llaves con los dominios de Localhost, técnicamente debería si o si funcionar.
