### ISSUE TITLE
subida de fotos

### ISSUE THREAD

**Issue by saotomaster** [MrDioamDev/risus2#2]
saludos... por alguna razon no puedo subir las fotos.... ni del pc ni linkearlas... siempore dice que la foto o la direccion no existe. como admin y como usuario.

Gracias

**Comment by MrDioamDev** [comment]
Hola.
Estoy revisando tu problema, al parecer a mi no me pasa pero retocaré algo para la siguiente release, posiblemente se arregle tu problema :D
